# Novelty Tree

In [2]:
import numpy as np
import pandas as pd
import sys, os, time

In [3]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [4]:
np.random.uniform(-1,1.01,)

array([0.23816448, 0.68155708])

In [ ]:
class BinaryTree:
    
    def __init__(self, parent, depth):
        self.parent = parent
        self.depth = depth
        self.child_r = None
        self.child_l = None
        self.d = None
        self.p = None
        self.coeff = None
        self.v = None
        self.visits = None
        self.split_type = 'simple'
    
    def generate_and_evaluate_planes(self, X, n_planes, n_cols=None):
        
        m,n = X.shape
        if n_cols is None:
            for i in range(n_planes):
                coeff = np.random.uniform(-1,1.000001,n)
                planes = None 
            
        else:
            pass
        
        self.split_type = 'plane'
        
    def simple_split(self,X,n_cols=None):
        
        m,n = X.shape
        if n_cols is None:
            col = int(np.random.randint(0,n+1,1))
            index = int(np.random.choice(m, 1))
            self.d = col
            self.p = X[index,col]
        else:
            cols = np.random.choice(n, n_cols,replace=False)
            col = int(np.random.choice(cols,1))
            index = int(np.random.choice(m, 1))
            self.d = col
            self.p = X[index,col]
            
        self.split_type = 'simple'
        
    def func(self, X):
        
        if self.split_type == 'simple':
            splitter = np.vectorize(lambda x : x >= self.p)
            indexes = splitter(X[:,self.d])
            right = X[!indexes,:]
            left = X[indexes,:]
            return right, left
        else:
            pass

In [ ]:
def simple_tree_builder(X):
    pass

In [5]:
X = np.random.uniform(-1,1,(100,10))
X.shape

(100, 10)

In [6]:
X

array([[-7.45311254e-01,  2.79738968e-01,  1.52424745e-01,
         8.06658238e-01, -8.14116446e-01,  1.38038417e-01,
         7.44923503e-01,  8.98403253e-01,  1.01879746e-01,
         3.87654542e-01],
       [-3.62333277e-01,  1.71501242e-01,  4.47932432e-01,
         4.37678974e-01, -1.08965410e-01,  2.40838525e-01,
        -9.95002051e-03,  1.87887443e-01,  8.42422738e-02,
         2.02675694e-01],
       [ 8.48001759e-02, -4.51843750e-01, -9.99983959e-01,
        -3.92793904e-01,  7.57579213e-01,  1.08100352e-02,
        -7.89492856e-01, -4.83000612e-01,  8.15223050e-01,
         2.24749074e-01],
       [ 3.91798062e-01, -4.67865211e-01,  6.42660952e-01,
        -9.60466059e-01,  7.69009102e-01, -9.64501446e-01,
         3.54615650e-01,  3.70107240e-01, -7.76993402e-01,
        -3.60393181e-01],
       [ 3.81308396e-01,  2.89431701e-01,  2.45925459e-01,
        -8.91364793e-01, -8.87977408e-01, -5.40626161e-01,
         4.09086821e-01, -7.03639883e-01,  8.00728011e-01,
         3.

In [7]:
from scipy.stats.stats import pearsonr 

In [8]:
pearsonr(X[:,1],X[:,2])

(0.07904404343602683, 0.43437511849103716)

In [9]:
import pandas as pd

In [11]:
df = pd.DataFrame(X)

In [13]:
df.corr()

0         1         2         3         4         5         6  \
0  1.000000  0.121466  0.095954 -0.047339 -0.019597 -0.018628 -0.104294   
1  0.121466  1.000000  0.079044 -0.110975 -0.030916 -0.143641 -0.081911   
2  0.095954  0.079044  1.000000  0.062556 -0.174823  0.019406  0.044622   
3 -0.047339 -0.110975  0.062556  1.000000  0.027361  0.008793  0.025405   
4 -0.019597 -0.030916 -0.174823  0.027361  1.000000 -0.079873 -0.109929   
5 -0.018628 -0.143641  0.019406  0.008793 -0.079873  1.000000 -0.095197   
6 -0.104294 -0.081911  0.044622  0.025405 -0.109929 -0.095197  1.000000   
7 -0.219844 -0.004645  0.013312 -0.101762  0.032084 -0.035649  0.010793   
8  0.159857 -0.075894 -0.187398 -0.033688  0.022997  0.203931 -0.126334   
9  0.040997  0.060607  0.013945 -0.075941 -0.013972 -0.043880 -0.152170   

          7         8         9  
0 -0.219844  0.159857  0.040997  
1 -0.004645 -0.075894  0.060607  
2  0.013312 -0.187398  0.013945  
3 -0.101762 -0.033688 -0.075941  
4  0.032084  0.022997 -0.013972  
5 -0.035649  0.203931 -0.043880  
6  0.010793 -0.126334 -0.152170  
7  1.000000 -0.040307 -0.013229  
8 -0.040307  1.000000  0.025325  
9 -0.013229  0.025325  1.000000

In [14]:
from numpy import linalg as LA

In [16]:
v = LA.eig(df.corr())

In [18]:
v

(array([1.44710059, 1.35652916, 1.25868744, 0.58864956, 1.11859919,
        1.01053077, 0.91865564, 0.7029918 , 0.80748528, 0.79077058]),
 array([[-0.39772099, -0.43069128,  0.22289534,  0.51565599, -0.21193049,
         -0.23461472, -0.12591288,  0.11413085,  0.44140014, -0.1306408 ],
        [-0.00215104, -0.55115973, -0.24613331,  0.01590079, -0.01071223,
         -0.14954143, -0.33385398, -0.4164992 , -0.55167695, -0.15371718],
        [ 0.2575365 , -0.41107944,  0.36516046, -0.45107426,  0.21473554,
          0.31744224, -0.28804579, -0.14887693,  0.41639553,  0.04977552],
        [ 0.10977802,  0.17426213,  0.3662263 ,  0.18315545, -0.45000739,
          0.5266206 , -0.07716313, -0.08889651, -0.21332573, -0.50071285],
        [-0.14012941,  0.22951373, -0.43776214, -0.07568061, -0.48397598,
          0.15111357, -0.28856086, -0.43525877,  0.36296054,  0.26229366],
        [-0.30303611,  0.28781201,  0.3759091 ,  0.34237743,  0.43914825,
          0.13585195, -0.21800495, -0.40054

In [20]:
v[1].shape

(10, 10)